name       : python-pyrfc3339
version    : 1.0
release    : 2
source     :
    - https://github.com/kurtraschke/pyRFC3339/releases/download/v1.0/pyRFC3339-1.0.tar.gz : 8dfbc6c458b8daba1c0f3620a8c78008b323a268b27b7359e92a4ae41325f535
license    : MIT
component  : programming.python
summary    : Parses and generates RFC 3339-compliant timestamps using Python datetime.datetime objects.
description: |
    Parses and generates RFC 3339-compliant timestamps using Python datetime.datetime objects.
builddeps  :
    - pkgconfig(python3)
    - python-pytz
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
